clients:
  - url: ${HISTORY_LOKI_HOST}/loki/api/v1/push   # Make sure this port matches your Loki http port
    basic_auth:
      username: ${HISTORY_LOKI_USERNAME}
      password: ${HISTORY_LOKI_PASSWORD}
    batchwait: 1m  # Maximum time to wait before sending a batch
    batchsize: 1024  # Maximum batch size in bytes
    backoff_config:
      min_period: 500ms  # Initial backoff time
      max_period: 5m    # Maximum backoff time
    timeout: 10s      # Maximum time to wait for server response
    tenant_id: "default"

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: shell_commands
    static_configs:
      - targets:
          - localhost
        labels:
          host: ${HOST}
          service_name: zsh
          __path__: ${HOME}/.shell/command_log
    
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{10,13}) (?P<command>.*)$'
      - timestamp:
          source: timestamp
          format: Unix
      - output:
          source: command  # Only send the command part to Loki
      - labeldrop:
          - filename
      # It is possible to label when parsing
      # - labels:
      #     host:
      #     service_name:

